language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
script: 
    - npm install -g serverless
    - sls deploy -v
stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
